import React from 'react'
import './AboutUs.css';

function AboutUs() {
  return (
    <>
          <div className='main1'>
          <h3 className='titles'>About Us</h3>
          <div  className='main'>

              
              <div className='card'>
                <img alt="Gold" src='person1.png' className='card-image'></img>
                <h2 className='card-title'>Naseem</h2>
                <p className='card-text'>Bachelor of Honors (B.Hons) degree in Software Engineering</p>
                <p className='score'>IIT</p>
              </div>

              <div className='card'>
                <img alt="Gold" src="silver.png" className='card-image'></img>
                <h2 className='card-title'>Anuda</h2>
                <p className='card-text'>Bachelor of Honors (B.Hons) degree in Software Engineering</p>
                <p className='score'>IIT</p>
              </div>

              <div className='card'>
                <img alt="Gold" src="platinum.png" className='card-image'></img>
                <h2 className='card-title'>Ruwinda</h2>
                <p className='card-text'>Bachelor of Honors (B.Hons) degree in Software Engineering</p>
                <p className='score'>IIT</p>
              </div>


              <div className='card'>
                <img alt="Gold" src='gold1.png' className='card-image'></img>
                <h2 className='card-title'>Aqeel</h2>
                <p className='card-text'>Bachelor of Honors (B.Hons) degree in Software Engineering</p>
                <p className='score'>IIT</p>
              </div>

              <div className='card'>
                <img alt="Gold" src="silver.png" className='card-image'></img>
                <h2 className='card-title'>Shimar</h2>
                <p className='card-text'>Bachelor of Honors (B.Hons) degree in Software Engineering</p>
                <p className='score'>IIT</p>
              </div>





          </div>
          </div>

          <div className='main2'>
            
            <div className='main-contents'>
              <p>
            In the realm of knowledge, where questions abound,<br/>
            Our journey begins, with curiosity unbound.<br/>
            Welcome to our haven, our About Us page,<br/>
            Crafted with care, for the wise and the sage.</p><br/>
            <p>
            Within these digital halls, questions reside,<br/>
            Challenges await, where knowledge is tried.<br/>
            Generated by algorithms, yet open to all,<br/>
            Naseem, Anuda, Ruwinda, Aqeel, and Shimar stand tall.</p><br/>
            <p>
            For the SDGP project, this venture we've made,<br/>
            A collaborative effort, where dreams cascade.<br/>
            With minds united, we've paved the way,<br/>
            For seekers of truth, to learn and to play.</p><br/>
            <p>
            Answer with confidence, for here you'll find,<br/>
            Accuracy measured, to enrich your mind.<br/>
            A journey of discovery, where learning thrives,<br/>
            In this sanctuary of knowledge, where wisdom arrives.</p><br/>
            <p>
            So venture forth, explore with delight,<br/>
            On this About Us page, where brilliance takes flight.<br/>
            With questions and answers, our hearts entwine,<br/>
            In the pursuit of knowledge, for all humankind's shine</p><br/>
            </div>
          </div>

          
    
    
    </>
  )
}

export default AboutUs
